# Generated by Django 3.2.13 on 2022-11-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre_ids',
        ),
    ]
